FROM openjdk:11

ARG DB_USERNAME=admin
ARG DB_PASSWORD=
ARG APP_PORT=8080
ARG APP_SECRET=thisisasecret
ARG APP_REQUEST_ORIGIN=*

ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV APP_PORT=$APP_PORT
ENV APP_SECRET=$APP_SECRET
ENV APP_REQUEST_ORIGIN=$APP_REQUEST_ORIGIN

RUN ./mvnw -Dmaven.test.skip=true install
COPY ./target/calculo-api-*.jar calculo-api-*.jar
CMD ["java", "-jar", "calculo-api-1.0.0.jar"]