version: "3"
services:
  server:
    image: calculo-api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - calculo-net
    depends_on:
      - psql-db

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calculo-net
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=calculo_db
      - POSTGRES_USER=${DB_USERNAME}

networks:
  calculo-net:

volumes:
  pgdata:
