version: "3"
services:
  server:
    image: calculo-api
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - calculo-net
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - APP_SECRET=${APP_SECRET}
      - APP_REQUEST_ORIGIN=${APP_REQUEST_ORIGIN}
      - APP_PORT=${APP_PORT:-8080}

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calculo-net
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}

networks:
  calculo-net:

volumes:
  pgdata:
