version: "3"
services:
  server:
    image: calculo-api
    ports:
      - "${PORT}:${PORT}"
    networks:
      - calculo-net
    depends_on:
      - db
    environment:
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGUSER=${PGUSER}
      - APP_SECRET=${APP_SECRET}
      - APP_REQUEST_ORIGIN=${APP_REQUEST_ORIGIN}
      - PORT=${PORT:-8080}

  db:
    image: postgres:13
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calculo-net
    environment:
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - POSTGRES_USER=${PGUSER}

networks:
  calculo-net:

volumes:
  pgdata:
