package db.migrations;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.SingleConnectionDataSource;

public class B1__Database extends BaseJavaMigration {

    @Override
    public void migrate(Context context) {
        new JdbcTemplate(new SingleConnectionDataSource(context.getConnection(), true))
                .execute(/* language=sql */
                        "CREATE TABLE users (\n" +
                        "  id BIGINT NOT NULL,\n" +
                        "   first_name VARCHAR(255) NOT NULL,\n" +
                        "   last_name VARCHAR(255) NOT NULL,\n" +
                        "   email VARCHAR(255) NOT NULL,\n" +
                        "   password_digest VARCHAR(255) NOT NULL,\n" +
                        "   created_at TIMESTAMP WITHOUT TIME ZONE,\n" +
                        "   updated_at TIMESTAMP WITHOUT TIME ZONE,\n" +
                        "   CONSTRAINT pk_users PRIMARY KEY (id)\n" +
                        ");\n" +
                        "\n" +
                        "ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);" +

                        "CREATE TABLE transactions (\n" +
                        "  id BIGINT NOT NULL,\n" +
                        "   title VARCHAR(255) NOT NULL,\n" +
                        "   notes TEXT,\n" +
                        "   total FLOAT NOT NULL,\n" +
                        "   user_id BIGINT,\n" +
                        "   created_at TIMESTAMP WITHOUT TIME ZONE,\n" +
                        "   updated_at TIMESTAMP WITHOUT TIME ZONE,\n" +
                        "   CONSTRAINT pk_transactions PRIMARY KEY (id)\n" +
                        ");\n" +
                        "\n" +
                        "ALTER TABLE transactions ADD CONSTRAINT FK_TRANSACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);" +

                        "CREATE TABLE roles (\n" +
                                "  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                                "   name VARCHAR(20),\n" +
                                "   CONSTRAINT pk_roles PRIMARY KEY (id)\n" +
                                ");"+

                        "CREATE TABLE refreshtoken (\n" +
                                "  id BIGINT NOT NULL,\n" +
                                "   user_id BIGINT,\n" +
                                "   token VARCHAR(255) NOT NULL,\n" +
                                "   expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,\n" +
                                "   CONSTRAINT pk_refreshtoken PRIMARY KEY (id)\n" +
                                ");\n" +
                                "\n" +
                                "ALTER TABLE refreshtoken ADD CONSTRAINT uc_refreshtoken_token UNIQUE (token);\n" +
                                "\n" +
                                "ALTER TABLE refreshtoken ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);" +

                        "CREATE TABLE categories (\n" +
                        "  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,\n" +
                        "   name VARCHAR(255),\n" +
                        "   CONSTRAINT pk_categories PRIMARY KEY (id)\n" +
                        ");"
                );
    }
}