CREATE TABLE IF NOT EXISTS categories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS roles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    password_digest VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS refreshtoken
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    token   VARCHAR(255) NOT NULL,
    user_id BIGINT
);

ALTER TABLE users ADD CONSTRAINT users_email_unique_constraint UNIQUE(email);

ALTER TABLE refreshtoken ADD CONSTRAINT refreshtoken_token_unique_constraint UNIQUE(token);

CREATE TABLE IF NOT EXISTS expense_categories
(
    expense_id BIGINT NOT NULL,
    category_id    BIGINT NOT NULL,
    CONSTRAINT expenses_categories_pkey PRIMARY KEY(expense_id, category_id)
);

CREATE TABLE IF NOT EXISTS expenses
(
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    notes TEXT,
    title VARCHAR(255) NOT NULL,
    total FLOAT4 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    user_id BIGINT
);

CREATE TABLE IF NOT EXISTS user_roles
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY(user_id, role_id)
);

ALTER TABLE expense_categories ADD CONSTRAINT fk4w5cqbyyhe713v88k32809a5i
FOREIGN KEY(expense_id)
REFERENCES expenses(id)
ON UPDATE
    NO ACTION
ON DELETE
    NO ACTION;

ALTER TABLE refreshtoken ADD CONSTRAINT fka652xrdji49m4isx38pp4p80p
FOREIGN KEY(user_id)
REFERENCES users(id)
ON UPDATE
    NO ACTION
ON DELETE
    NO ACTION;

ALTER TABLE user_roles ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6
FOREIGN KEY(role_id)
REFERENCES roles(id)
ON UPDATE
    NO ACTION
ON DELETE
    NO ACTION;

ALTER TABLE user_roles ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f
FOREIGN KEY(user_id)
REFERENCES users(id)
ON UPDATE
    NO ACTION
ON DELETE
    NO ACTION;

ALTER TABLE expense_categories ADD CONSTRAINT fkl8nhemttklbafivosqgyv35rl
FOREIGN KEY(category_id)
REFERENCES categories(id)
ON UPDATE
    NO ACTION
ON DELETE
    NO ACTION;

ALTER TABLE expenses ADD CONSTRAINT fkqwv7rmvc8va8rep7piikrojds
FOREIGN KEY(user_id)
REFERENCES users(id)
ON UPDATE
    NO ACTION
ON DELETE
    NO ACTION;

INSERT INTO categories (id, name) VALUES(1, 'CATEGORY_GROCERIES');
INSERT INTO categories (id, name) VALUES(2, 'CATEGORY_GENERAL');
INSERT INTO categories (id, name) VALUES(3, 'CATEGORY_CHARITY');
INSERT INTO categories (id, name) VALUES(4, 'CATEGORY_ENTERTAINMENT');
INSERT INTO categories (id, name) VALUES(5, 'CATEGORY_FINANCES');
INSERT INTO categories (id, name) VALUES(6, 'CATEGORY_EATING_OUT');
INSERT INTO categories (id, name) VALUES(7, 'CATEGORY_PERSONAL_CARE');
INSERT INTO categories (id, name) VALUES(8, 'CATEGORY_GIFTS');
INSERT INTO categories (id, name) VALUES(9, 'CATEGORY_HOLIDAYS');
INSERT INTO categories (id, name) VALUES(10, 'CATEGORY_BILLS');
INSERT INTO categories (id, name) VALUES(11, 'CATEGORY_FAMILY');
INSERT INTO categories (id, name) VALUES(12, 'CATEGORY_SHOPPING');
INSERT INTO categories (id, name) VALUES(13, 'CATEGORY_TRAVEL');

INSERT INTO roles (id, name) VALUES(1, 'ROLE_ADMIN');
INSERT INTO roles (id, name) VALUES(2, 'ROLE_USER');
